#define CONFIG_PS2K_INITIAL_BUF_SIZE 512
#define CONFIG_PS2K_ALLOC_BUF_MALLOC 1
#define CONFIG_PS2K_ALLOC_BUF 1
#define CONFIG_ACPI_VERBOSE 1
#define CONFIG_PIT_FREQUENCY 300
#define CONFIG_EXCEPTIONS_NESTING_THRESHOLD 3
#define CONFIG_NUM_PROC 128
#define CONFIG_STACK_SIZE 8192
